### ISSUE TITLE
Ontwerp - responsief

### ISSUE THREAD

**Issue by Nazneen05x** [Naddybs/the-startup-responsive-interactieve-website#11]
Hoi Nadira,

Ik zou nog naar je ontwerp kijken en je had verteld dat je moeite had met responsief dus ik heb wat artikelen voor je die je kan doornemen. Als je nog steeds vast loopt kan je altijd om hulp vragen.

## Ontwerp
- Broodtekst uitlijnen met de titel en button.
- Meer witruimte (padding) boven de tekst.

- Witte vlak met tekst mag meer witruimte (padding).
- Tekst met button meer in het midden centreren.

<img width="200" alt="ontwerp" src="https://github.com/Naddybs/the-startup-responsive-interactieve-website/assets/112861261/568a9fb3-2146-4d4c-9c15-bb12e29a69c2">

-----
- Afbeelding en tekst meer in het midden.
- Not sure yet, en logo meer in het midden.

<img width="200" alt="ontwerp" src="https://github.com/Naddybs/the-startup-responsive-interactieve-website/assets/112861261/743b9f19-959e-4382-a15a-c6cacf7fe4db">

----

- Stappenplan heel leuk gemaakt! zou leuk zijn als je hier een animatie aan geeft.
- Het zou leuk zijn als je de hele footer kan maken.

## Responsief:

Ik heb wat artikelen die je kan lezen die je misschien kan helpen betreft responsief. 

### Media Queries:

[https://css-tricks.com/a-complete-guide-to-css-media-queries/](url)
[https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Media_queries](url)
[https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries](url)

### Grid 

Altijd goed om je website met grid responsief te maken.

[https://developer.mozilla.org/en-US/docs/Web/CSS/grid](url)

**Comment by Naddybs** [comment]
Bedankt voor de feedback! Ik heb je feedback goed doorgelezen en ik ben het ermee eens. Daarbij heb ik me ook niet helemaal gehouden aan mijn oorspronkelijke designs. Ik zal je verder feedback meenemen. Wat betreft responsiveness vind ik het super handig dat je me deze bronnen hebt gestuurd ik ga ze doornemen.
