### ISSUE TITLE
Usertest en feedback

### ISSUE THREAD

**Issue by Marwaxhello** [Naddybs/the-startup-responsive-interactieve-website#12]
Ik heb een usability test op je website uitgevoerd, waarbij ik door je Lifely Mobileverse-website heb genavigeerd. Ik begreep dat het om een AI ging en de bijbehorende informatie. Je website ziet er over het algemeen goed uit.

Tijdens mijn test merkte ik op dat ik niet meteen doorhad hoe ik naar andere secties kon gaan, aangezien alle inhoud al bovenaan de pagina leek te staan. Je legde uit dat dit overeenkomt met de officiële opdracht, wat voor mij prima is.

Ik heb enkele stappen doorlopen en viel op dat de kopjes duidelijk en leesbaar waren, wat het begrijpen vergemakkelijkte.

Een punt dat ik later besefte, was dat ik niet meteen doorhad dat ik kon scrollen om de carrousel helemaal onderaan de pagina te bekijken. Dit heb je me later toegelicht.

Wat betreft je code, heb ik geen problemen opgemerkt; alles lijkt prima te functioneren. Een suggestie die ik heb, is om comments toe te voegen aan je CSS of HTML om de code begrijpelijker te maken en te voorkomen dat je vergeet wat bepaalde delen doen. Ook raad ik aan om in plaats van br-tags spans te gebruiken.

Je hebt me laten zien wat je nog wilt bereiken met je website, en ik heb je laten weten dat ik bronnen via Teams zal sturen.

**Comment by Naddybs** [comment]
Dankjewel voor het meehelpen en het uitvoeren van een usertest!! Ik heb je feedback geïmplementeerd in mijn wiki, en zal deze verwerken in mijn site :) > https://github.com/Naddybs/the-startup-responsive-interactieve-website/wiki/Testen%F0%9F%94%8C
