### ISSUE TITLE
HTML Validator: <img> lijkt geen alt attribuut te hebben

### ISSUE THREAD

**Issue by zainablfz** [Naddybs/the-startup-responsive-interactieve-website#14]
https://github.com/Naddybs/the-startup-responsive-interactieve-website/blob/a49d4504c9a6fe9fa01fa4293d0c7474727618e1/index.html#L14

https://github.com/Naddybs/the-startup-responsive-interactieve-website/blob/a49d4504c9a6fe9fa01fa4293d0c7474727618e1/index.html#L103

De `<img>` heeft geen alt attribuut in de `HTML`. 

Het is beter voor o.a. de toegankelijkheid om hier een alt aan toe te voegen. 

Hier kun je meer lezen over de alt attribuut: 

- https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt
- https://www.a11yproject.com/posts/alt-text/

Verder ben je goed bezig! Je pagina ziet er tot nu toe goed uit

**Comment by Naddybs** [comment]
Dankjewel voor de feedback!! Ik heb de linkjes doorgenomen, en mijn code aangepast.

<img width="1440" alt="Schermafbeelding 2024-01-22 om 15 41 37" src="https://github.com/Naddybs/the-startup-responsive-interactieve-website/assets/144009698/37686990-240b-4aca-b042-eb54f6311e3d">
<img width="1440" alt="Schermafbeelding 2024-01-22 om 15 39 55" src="https://github.com/Naddybs/the-startup-responsive-interactieve-website/assets/144009698/9429f8ed-bf5c-41c4-be48-66da041c83da">
