### ISSUE TITLE
Gebruik van `<li>`  ipv een ander element

### ISSUE THREAD

**Issue by KaanKalmi** [Naddybs/the-startup-responsive-interactieve-website#15]
<img src="https://github.com/Naddybs/the-startup-responsive-interactieve-website/assets/144000125/ce79c077-5248-47ba-bc8c-572850a6ccbf" height=450px>

[Codeblok](https://github.com/Naddybs/the-startup-responsive-interactieve-website/blob/bff51dd2308a7636e76e8559b03e416124c5899d/index.html#L143-L168)

Ik zie hier dat je list items gebruikt voor kaarten, kan je niet een ander element gebruiken (denk aan articles!)

Evt kan je deze bronnen gebruiken:

- [MDN List Item ELement](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li)
- [MDN Article Element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article)

**Comment by Naddybs** [comment]
https://github.com/Naddybs/the-startup-responsive-interactieve-website/blob/d91c77a4d2b44eb459772245831e92905b096c39/index.html#L118-L144

**Dankjewel voor de feedback!**
Ik heb de bronnen doorlezen, handig bedankt. In dit specifieke geval is het wel geschikt om een lijst te gebruiken voor het weergeven van kaarten.  Ik gebruik het namelijk om een sectie te vormen met verzamelde items inplaats van het gebruik van individuele artikelen.
