### ISSUE TITLE
alt toevoegen bij img

### ISSUE THREAD

**Issue by Pink-Mallow** [Naddybs/the-startup-responsive-interactieve-website#16]
Bij sommige images heb je geen alt="" erbij gezet. Ik zie het wel bij sommigen maar niet overal. Probeer dit eventueel toe te voegen. Dit is gunstig voor screenreaders.

Voor extra uitleg:
[alt uitleg](https://www.freecodecamp.org/news/what-is-alt-text-image-alt-text-html-example/)

**Comment by Naddybs** [comment]
Dankjewel voor de feedback!! Ik heb het linkje doorgenomen, en mijn code aangepast.

<img width="1440" alt="Schermafbeelding 2024-01-22 om 15 41 37" src="https://github.com/Naddybs/the-startup-responsive-interactieve-website/assets/144009698/37686990-240b-4aca-b042-eb54f6311e3d">
<img width="1440" alt="Schermafbeelding 2024-01-22 om 15 39 55" src="https://github.com/Naddybs/the-startup-responsive-interactieve-website/assets/144009698/9429f8ed-bf5c-41c4-be48-66da041c83da">
