### ISSUE TITLE
Schedule a free AI consultation positioneren

### ISSUE THREAD

**Issue by J3SS3HVA** [Naddybs/the-startup-responsive-interactieve-website#3]
Probeer deze button naar links te zetten, zodat het er beter uitziet

**Comment by Naddybs** [comment]
https://github.com/Naddybs/the-startup-responsive-interactieve-website/blob/bff51dd2308a7636e76e8559b03e416124c5899d/styles/header.css#L43-L53

Gefixt, thanks!
