### ISSUE TITLE
Hier kun je in de plaats van divs een lijst element van maken

### ISSUE THREAD

**Issue by Jason2426** [Naddybs/the-startup-responsive-interactieve-website#5]
https://github.com/Naddybs/the-startup-responsive-interactieve-website/blob/9f6cdf67642c95758acaa816de292f2a42c6dfab/index.html#L65C1-L105

**Comment by Naddybs** [comment]
'''HTML
 <section class="design-sprint-steps">
     <h2>What are the steps of the ai design sprint?</h2>
         <ul>
             <li>
                 <article>
                  <svg xmlns="http://www.w3.org/2000/svg" height="30" width="28" viewBox="0 0 320 512"><path fill="#3c3b34" d="M0 192C0 103.6 71.6 32 160 32s160 71.6 160 160V320c0 88.4-71.6 160-160 160S0 408.4 0 320V192zM160 96c-53 0-96 43-96 96V320c0 53 43 96 96 96s96-43 96-96V192c0-53-43-96-96-96z"/></svg>
                  <svg xmlns="http://www.w3.org/2000/svg" height="30" width="28" viewBox="0 0 256 512"><path fill="#3c3b34" d="M160 64c0-11.8-6.5-22.6-16.9-28.2s-23-5-32.8 1.6l-96 64C-.5 111.2-4.4 131 5.4 145.8s29.7 18.7 44.4 8.9L96 123.8V416H32c-17.7 0-32 14.3-32 32s14.3 32 32 32h96 96c17.7 0 32-14.3 32-32s-14.3-32-32-32H160V64z"/></svg>
                  <h3> We research your process</h3>
                  <p>We bring together your team to get your current process on paper. When we know the goals and output of your process we can effectively validate if we have successfully supported or replaced parts with AI solutions. </p>
                 </article>
            </li>
''' 
**Dankjewel voor de feedback!**
Ik begrijp nu beter dat het gebruik van een lijst met li elementen en article elementen inplaats van div elementen de semantiek, toegankelijkheid, onderhoud van styling en leesbaarheid kan verbeteren. Ik heb daarom dus ook mijn code veranderd en je feedback toegepast.
