### ISSUE TITLE
Je SVG overlapping probleempje

### ISSUE THREAD

**Issue by KaanKalmi** [Naddybs/the-startup-responsive-interactieve-website#9]
Wat je mist is een div om je svgs heen waar je de class svg-background hebt,
![image](https://github.com/Naddybs/the-startup-responsive-interactieve-website/assets/144000125/9c38c310-f266-4b78-80bd-4be02a38026f)
Hierna moest je in ieder geval de volgende css toevoegen eraan:
` .svg-background {  position: absolute;  width: 100%; height: 100%; overflow: hidden; z-index: 2;  }`

Dit zorgt er namelijk voor dat je svg-background divje 100% van de hoogte en breedte is van je scherm en ook nog is boven je 
`<div class="intro-content"` tevoorschijn komt

Hierna moest je de svg met de classes `svg-top-right` en `svg-bottom-left` nog is aanpassen met als `z-index` = 0 zodat het onder je tekst overlapped, daarna kan je lekker spelen met de positioning en sizing!

nu denk je zeker maar waarom doe je hier geen `overflow=hidden`? Dit komt omdat je `overflow` alleen werkt op elementen met content erin, en je svg heeft geen content erin!

Eindresultaat zou moeten lijken hierop:
![image](https://github.com/Naddybs/the-startup-responsive-interactieve-website/assets/144000125/881dbada-f4d8-47e6-8034-6f88eafbcdb7)

**Comment by Naddybs** [comment]
Dankjewel voor de hulp!! Hij staat in deze commit > https://github.com/Naddybs/the-startup-responsive-interactieve-website/commit/bff51dd2308a7636e76e8559b03e416124c5899d
